model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

[features]
web_search_request = true

[projects."/Users/danielchen/projects/ytlm"]
trust_level = "trusted"

[projects."/Users/danielchen/code/homebot"]
trust_level = "trusted"

[projects."/Users/danielchen"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
